Bump runtime to 42 and oomox to 1.14
flathub/com.github.themix_project.Oomox pull request #9
Opened 2022-07-19 05:19 UTC by bbhtt

- Update resvg to 0.23.0, add cargo manifest and add new build commands
- Update Pillow to 9.2.0, haishoku to 1.1.8
- Add pystache and pyyaml for Base16 format
- Update libsass to 3.6.5 and sassc to 3.6.2
- Update ImageMagick to 7.1.0.43
- Update oomox to 1.14

This built and ran fine locally but I don't use the app, so needs testing to see if it still works. 

It ran fine in native wayland, so I added support for it. If there are issues or wayland is unsupported entirely I can drop that change. :)

Ping @actionless, please review when you have time, thanks!

2022-07-19 05:26 UTC, bbhtt commented
https://github.com/flathub/com.github.themix_project.Oomox/blob/95182c1329446f24d04f6150b840e2a1307d3f76/flathub.json#L2 

Is skipping appstream validation still needed? There's no reason specified on why it is being skipped and the build logs are gone 

Running `flatpak run --env=G_DEBUG=fatal-criticals org.freedesktop.appstream-glib validate *.xml` locally, it passes. So I'm removing it. If there are issues I'll re-add.

2022-07-19 05:28 UTC, bbhtt commented
bot, build

2022-07-19 11:14 UTC, actionless commented
if i understood the log right it's failing on this:

```
appstream-compose --prefix=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-FbyLAP/files --origin=flatpak --basename=com.github.themix_project.Oomox com.github.themix_project.Oomox
```

with many error, main of which probably:

```
cannot open display: 
```

2022-07-19 12:14 UTC, hfiguiere requested changes

2022-07-19 12:18 UTC, actionless commented on com.github.themix_project.Oomox.json
> +            },
thanks!

2022-07-19 12:19 UTC, hfiguiere commented
> if i understood the log right, it's failing on this:
> 
> ```
> appstream-compose --prefix=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-FbyLAP/files --origin=flatpak --basename=com.github.themix_project.Oomox com.github.themix_project.Oomox
> ```
> 
> with many errors, main of which probably:
> 
> ```
> cannot open display: 
> ```

these are harmless.

2022-07-19 12:20 UTC, actionless commented on com.github.themix_project.Oomox.json
> -                    "url": "https://github.com/sass/sassc/archive/3.4.2.tar.gz",
don't do this - it will break Arc theme

2022-07-19 12:20 UTC, actionless commented on com.github.themix_project.Oomox.json
> -                    "sha256": "855c40528b897d06ae4d24606c2db3cd09bb38de5b46b28e835f9d4fd4d7ab95",
same

2022-07-19 12:22 UTC, hfiguiere commented
I'm pretty this part:
```
                "mkdir -p /app/usr/share/",
                "ln -s /app/share/applications /app/usr/share/applications",
                "ln -s /app/share/appdata /app/usr/share/appdata",
                "ln -s /app/share/icons /app/usr/share/icons"
```

is part of the problem. `/app/usr` trigger bugs in appstream and has no reason to exist.

2022-07-19 12:23 UTC, actionless commented on com.github.themix_project.Oomox.json
> -                    "url": "https://github.com/sass/sassc/archive/3.4.2.tar.gz",
https://github.com/themix-project/oomox/issues/293#issuecomment-608345676

2022-07-19 12:29 UTC, actionless commented
@hfiguiere i've tried to remove it - let's see

2022-07-19 12:38 UTC, actionless commented
or mb actually this is the problem, not symlinks:

```
Error loading desktop file: Failed to find icon: Failed to find icon com.github.themix_project.Oomox
Error: ERROR: appstream-compose failed: Child process exited with code 1
```

2022-07-19 13:23 UTC, actionless commented
thanks @hfiguiere it apparently helped

2022-07-19 13:34 UTC, hfiguiere commented
> thanks @hfiguiere it apparently helped

as I said, it triggers unfixed bugs in appstream-glib, and that's the root of the problems with icons when they actually are installed.
In general `/app/usr` remain a bad idea, and is totally off the filesystem standards. (`/app/opt` as well btw)

2022-07-19 13:37 UTC, hfiguiere requested changes

2022-07-19 13:37 UTC, hfiguiere commented on com.github.themix_project.Oomox.json
> +            "build-options": {
nor sure why this was moved here. Affects readability, and make the patch bigger.

2022-07-19 14:23 UTC, bbhtt commented on com.github.themix_project.Oomox.json
> +            "build-options": {
Thanks, that was unintentional. Fixed.

2022-07-19 14:24 UTC, bbhtt commented on com.github.themix_project.Oomox.json
> -                    "sha256": "855c40528b897d06ae4d24606c2db3cd09bb38de5b46b28e835f9d4fd4d7ab95",
Pined to 3.6.1 which was confirmed as working

2022-07-19 14:24 UTC, bbhtt commented on com.github.themix_project.Oomox.json
> -                    "url": "https://github.com/sass/sassc/archive/3.4.2.tar.gz",
Pinned to 3.6.1 which was confirmed as working

2022-07-19 14:26 UTC, bbhtt commented
I squashed the i386 commits and cleaned up the rest. Hope you don't mind.

Thanks!

2022-07-19 14:29 UTC, actionless commented
thanks! please let me know if it will work for you after the build

2022-07-20 01:39 UTC, bbhtt commented
Hi, I've tested it out with the bluloco theme, it can export those to ~/.themes and the icon theme in ~/.icons. Let me know if this is fine.

2022-07-20 01:40 UTC, actionless commented
thanks @bbhtt let's see :)

2022-07-20 01:41 UTC, merged